export const imagesList = [
    "src/assets/Images/img01.jpg",
    "src/assets/Images/img02.jpg",
    "src/assets/Images/img03.jpg",
    "src/assets/Images/img04.jpg",
    "src/assets/Images/img05.jpg",
    "src/assets/Images/img06.jpg",
    "src/assets/Images/img07.jpg",
    "src/assets/Images/img08.jpg",
    "src/assets/Images/img09.jpg",
    "src/assets/Images/img10.jpg",
    "src/assets/Images/img11.jpg",
    "src/assets/Images/img12.jpg",
    "src/assets/Images/img13.jpg",
    "src/assets/Images/img14.jpg",
    "src/assets/Images/img15.jpg",
    "src/assets/Images/img16.jpg",
    "src/assets/Images/img17.jpg",
    "src/assets/Images/img18.jpg",
    "src/assets/Images/img19.jpg",
    "src/assets/Images/img20.jpg",
]

export const now_plaing_movies = [
    { image: "src/assets/Images/img01.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
    { image: "src/assets/Images/img02.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
    { image: "src/assets/Images/img03.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
    { image: "src/assets/Images/img04.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
    { image: "src/assets/Images/img05.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
    { image: "src/assets/Images/img06.jpg" ,
    title:"Zootopia", desctiption:"This is a movie containing rabbit and some other animals inside a city and so on and on until they find something that has to be amazing and this is something that is great in terms of something and this whole text is just a placeholder and does not make any sense if you are confused about it."},
]